apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - image: ghcr.io/openearthplatforminitiative/weather-api:0.0.9
          name: weather-api
          ports:
            - containerPort: 8080
          env:
            - name: API_ROOT_PATH
              value: "/weather"
            - name: VERSION
              value: "0.0.9"
---
apiVersion: v1
kind: Service
metadata:
  name: weather-api
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: weather-api
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: weather-api
spec:
  http:
    - name: weather-api
      match:
        paths:
          - /weather/*
      backends:
        - serviceName: weather-api
          servicePort: 80
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/weather/(.*)"
              - "/$1"
