apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - image: ghcr.io/openearthplatforminitiative/weather-api:0.1.4
          name: weather-api
          ports:
            - containerPort: 8080
          env:
            - name: API_ROOT_PATH
              value: "/weather"
            - name: VERSION
              value: "0.1.4"
            - name: API_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: openepi-apps-config
                  key: api_domain
---
apiVersion: v1
kind: Service
metadata:
  name: weather-api
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: weather-api
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix-weather
spec:
  stripPrefix:
    prefixes:
      - /weather
    forceSlash: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weather-api
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: PathPrefix(`/weather`) && !PathPrefix(`/weather/metrics`)
    services:
    - kind: Service
      name: weather-api
      port: 80
    middlewares:
    - name: stripprefix-weather
